# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-27 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AditionalMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_key', models.CharField(max_length=100)),
                ('metadata_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTagMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreateAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('asset_name', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
                ('size', models.CharField(max_length=100)),
                ('activate_on', models.DateField(null=True)),
                ('expire_on', models.DateField(null=True)),
                ('thumbnail', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CreateAssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CreateTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='createasset',
            name='asset_typeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanagement.CreateAssetType'),
        ),
        migrations.AddField(
            model_name='createasset',
            name='folder_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_api.Folders'),
        ),
        migrations.AddField(
            model_name='comments',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanagement.CreateAsset'),
        ),
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetmanagement.Comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettagmapping',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanagement.CreateAsset'),
        ),
        migrations.AddField(
            model_name='assettagmapping',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanagement.CreateTags'),
        ),
        migrations.AddField(
            model_name='aditionalmetadata',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetmanagement.CreateAsset'),
        ),
    ]
