# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createasset',
            name='asset',
        ),
        migrations.AddField(
            model_name='createasset',
            name='asset_path',
            field=models.CharField(default=' ', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createasset',
            name='asset_name',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='createasset',
            name='thumbnail',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='createassettype',
            name='asset_type',
            field=models.CharField(max_length=50),
        ),
    ]
