# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganization',
            name='user_org_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_org_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
