# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('role_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='username',
        ),
        migrations.AddField(
            model_name='userorganization',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='organization_id',
            field=models.CharField(max_length=10),
        ),
    ]
