# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20190307_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=50)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userorganization',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
