# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20190314_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='user_org_id',
            new_name='user_role_id',
        ),
    ]
