# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20190313_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=30),
        ),
    ]
