# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20190313_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userorganization',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserOrganization',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
