# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20190312_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganization',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
