# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20190313_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Role'),
        ),
    ]
